### ISSUE TITLE
message filtering

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#339]
allow only img, a, br tag in message, filter & change others
make anchor if sentence starts with "http://"

**Comment by kws4679** [comment]
If the text contains anchor tag already, it is a little bit annoying to extract and identify whether url should be transformed or not. So if the text contains already, then it will not be changed. Otherwise, sentence begins with "http://" will be changed.

**Comment by kws4679** [comment]
only img, a, br tag allowed. script tag will be transformed

**Comment by hoglahoo** [comment]
As far as I can tell, the img tag is not working correctly in messages

**Comment by hoglahoo** [comment]
Ok so it works with images stored on eterna's server.  It is not handling outside image urls very well.  Example: http://prntscr.com/1n7z46

**Comment by kws4679** [comment]
Thanks hoglahoo, that has been fixed

**Comment by hoglahoo** [comment]
Not sure what is happening, but it is still not working correctly for me.  When I use for example (img src="https://www.google.com/logos/doodles/2013/50th_anniversary_of_the_i_have_a_dream_speech-2072005.2-hp.jpg" /) then the image shows up.  But when I use (img src="http://img541.imageshack.us/img541/7428/ks0u.png" /) then it does not.

After trying a dozen images, it appears that anything with https:// will go through alright, but http:// is still having issues.  Not sure if it is just me

**Comment by lullujune** [comment]
Just- please check if this issue has been resolved or not
